image: node:latest

before_script:
  - apt-get -qq update
  - apt-get install -y jq

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

build_and_test_contracts:
  script:
    - npm install
    - ./node_modules/.bin/truffle compile
    - ./node_modules/.bin/testrpc &> /dev/null & ./node_modules/.bin/truffle test
    - for file in build/contracts/*.json; do jq '.abi' < "$file" > "${file%.json}.abi"; done
    - for file in build/contracts/*.json; do jq -r '.bytecode' < "$file" > "${file%.json}.bin"; done
  artifacts:
    paths:
      - build/
    expire_in: 1 month

